# Generated by Django 3.1.3 on 2020-12-03 19:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommunicationCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("accepted_keywords", models.TextField(blank=True)),
                ("bot_answer", models.TextField(blank=True)),
            ],
        ),
    ]
