# Generated by Django 3.1.3 on 2020-12-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamebot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="communicationcategory",
            name="link_url",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
